# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Derived from x11-misc/ly in ::guru (itself generated by zig-ebuilder
# 0.3.0), bumped from 1.4.1 to 1.5.0_rc1 and keyworded for arm64.

EAPI=8

DESCRIPTION="Ly - a TUI display manager"
HOMEPAGE="https://codeberg.org/fairyglade/ly"

# Keys are the Zig package hashes the build expects to find in the --system
# directory, so they must match build.zig.zon byte for byte; values are the
# tarball equivalents of upstream's "git+" URIs. 1.5.0 adds Lua animation
# support, which pulls in zlua and, through it, LuaJIT and a second copy of
# translate-c (zlua pins an older commit than ly-core/ly-ui do).
#
# Note that LuaJIT is a *lazy* dependency of zlua. "zig build --fetch" does
# not pull it, but ly asks zlua for -Dlang=.luajit unconditionally, so the
# build fails without it. Anything dropped here shows up as
# "lazy dependency package not found" at src_compile, not at fetch time.
declare -g -r -A ZBS_DEPENDENCIES=(
	[aro-0.0.0-JSD1Qi7QNgDnfcrdEJf82v3o6MhZySjYVrtdfEf3E4Se.tar.gz]='https://github.com/Vexu/arocc/archive/5f5a050569a95ecc40a426f0c3666ae7ef987ede.tar.gz'
	[clap-0.11.0-oBajB7foAQC3Iyn4IVCkUdYaOVVng5IZkSncySTjNig1.tar.gz]='https://github.com/Hejsil/zig-clap/archive/fc1e5cc3f6d9d3001112385ee6256d694e959d2f.tar.gz'
	[ini-0.1.0-YCQ9YiwsAACghqF8LZyjAF2H_NnL6n29QLuCe0fsmPTo.tar.gz]='https://github.com/AshAmetrine/ziglibs-ini/archive/3b733e10adc6c4c48050709b97a22258bc2e6156.tar.gz'
	[translate_c-0.0.0-Q_BUWpf0BgAwrh5AM-acJcslN_YPEhcoCVKbbNjwuUTJ.tar.gz]='https://codeberg.org/ziglang/translate-c/archive/46b5609b5ac4c0a896217d1d984f3ae50e4810b5.tar.gz'
	[translate_c-1.0.0-Q_BUWo_5BgD4flHdUhA31zOz0XvZk9k7lQv1ouzyNXj2.tar.gz]='https://codeberg.org/ziglang/translate-c/archive/6fe0ffc4549f15c5f2d9432c2b4460ba90ff85ac.tar.gz'
	[zigini-0.5.0-BSkB7e9WAACfyCBABNZiWL3gFMw18GKn3qBcPs8L1Ec1.tar.gz]='https://github.com/AshAmetrine/zigini/archive/a665d081dda42664a96da2840ea09c5ccf9d0692.tar.gz'
	[zlua-0.1.0-hGRpC2aABQD4D9PBVH3wAW8k32-I4969MRQ0CpOwoley.tar.gz]='https://github.com/natecraddock/ziglua/archive/8f271c82baa5fc43aa02a72f6da020c2025d9436.tar.gz'
	# termbox2 and LuaJIT declare no name in their build.zig.zon, so Zig
	# addresses them by bare hash.
	[N-V-__8AAAUXBQD6Fwpi9m0MBqWXFFaqW5l1lVrJC2Ynj7a-.tar.gz]='https://github.com/AnErrupTion/termbox2/archive/c7f241e8888ce243e1748b05c26a42fcfaaad936.tar.gz'
	[N-V-__8AAODpQgCVrpfzE2ze9FA_rOuByh3WKyIyk5iS_o9a.tar.gz]='https://github.com/LuaJIT/LuaJIT/archive/18b087cd2cd4ddc4a79782bf155383a689d5093d.tar.gz'
)

ZIG_SLOT="0.16"
# Left to its own devices zig.eclass generates
# "|| ( dev-lang/zig:0.16[llvm] dev-lang/zig-bin:0.16 )", and portage is free
# to satisfy that with dev-lang/zig -- a full LLVM-backed source bootstrap of
# the compiler. The prebuilt aarch64 toolchain is keyworded and produces the
# same thing, so go optional and depend on it directly. The cost is that no
# phase functions are exported and BDEPEND/QA_FLAGS_IGNORED are ours to set.
ZIG_OPTIONAL=1

inherit pam systemd zig

MY_PV="${PV/_rc/-rc}"

SRC_URI="
	https://codeberg.org/fairyglade/${PN}/archive/v${MY_PV}.tar.gz -> ${P}.tar.gz
	${ZBS_DEPENDENCIES_SRC_URI}
"

S="${WORKDIR}/${PN}"

# ly itself is WTFPL-2; MIT covers the statically linked LuaJIT, termbox2,
# zlua, zig-clap, zigini and translate-c/aro.
LICENSE="WTFPL-2 MIT"
SLOT="0"
KEYWORDS="-* ~arm64"

IUSE="X"

DEPEND="
	sys-libs/pam
	X? (
		x11-libs/libxcb
	)
"
RDEPEND="
	${DEPEND}
	app-misc/brightnessctl
	X? (
		x11-base/xorg-server
		x11-apps/xauth
		x11-apps/xrdb
		x11-apps/xmessage
	)
"
# zig-bin is always built with LLVM, which ly needs: Zig compiles termbox2
# and LuaJIT from C.
BDEPEND="
	virtual/pkgconfig
	dev-lang/zig-bin:${ZIG_SLOT}
"

# https://github.com/ziglang/zig/issues/3382
# The Zig Build System ignores CFLAGS/LDFLAGS outright.
QA_FLAGS_IGNORED="usr/bin/ly"

pkg_setup() {
	zig_pkg_setup
}

src_unpack() {
	zig_src_unpack
}

src_prepare() {
	zig_src_prepare

	# Upstream's own installer (install.zig, the "installexe" step) expands
	# these; we install by hand instead, so do the same substitutions here.
	sed -e "s|\$PREFIX_DIRECTORY|/usr|g" \
		-e "s|\$EXECUTABLE_NAME|ly|g" \
		-e "s|\$DEFAULT_TTY|2|g" \
		-e "s|\$CONFIG_DIRECTORY|/etc|g" \
		-i "${S}/res/${PN}@.service" \
		-i "${S}/res/${PN}-kmsconvt@.service" \
		-i "${S}/res/${PN}-openrc" \
		-i "${S}/res/config.ini" || die
}

src_configure() {
	local my_zbs_args=(
		-Denable_x11_support=$(usex X true false)
	)

	zig_src_configure
}

src_compile() {
	zig_src_compile
}

src_test() {
	zig_src_test
}

src_install() {
	zig_src_install

	dodoc readme.md
	newdoc res/custom-sessions/README custom-sessions

	newinitd "${S}/res/${PN}-openrc" ${PN}

	systemd_dounit "${S}/res/${PN}@.service"
	systemd_dounit "${S}/res/${PN}-kmsconvt@.service"

	insinto "/etc/${PN}"
	doins "${S}/res/config.ini"
	# Referenced by animation = dur_file / lua in the shipped config.ini.
	doins "${S}/res/example.dur"
	doins "${S}/res/example.lua"

	exeinto "/etc/${PN}"
	doexe "${S}/res/setup.sh"
	doexe "${S}/res/startup.sh"

	insinto "/etc/${PN}/lang"
	doins "${S}/res/lang/"*.ini

	keepdir "/etc/${PN}/custom-sessions"

	newpamd "${S}/res/pam.d/ly-linux" ly
	# config.ini defaults to auto_login_service = ly-autologin.
	newpamd "${S}/res/pam.d/ly-linux-autologin" ly-autologin
}

pkg_postinst() {
	elog "Enable Ly with:"
	elog "    rc-update add ly default"
	elog
	elog "Ly takes over tty2 by default, which Gentoo's stock /etc/inittab"
	elog "also gives an agetty. Either comment out the c2 line there or"
	elog "point 'tty' in /etc/ly/config.ini at a free VT."
}
